apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-gke-deployment
  labels:
    app: server-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: deploy-gke-server
          image: app-name
          ports:
            - containerPort: 8080
